import Link from "next/link";
const data:Record<string,{label:string,title:string,copy:string,img:string,cta:string}>={
 properties:{label:"THE PRIVATE COLLECTION",title:"Properties of distinction",copy:"A curated portfolio of residences selected for architecture, setting and an unmistakable sense of place.",img:"photo-1600607688969-a5bfcd646154",cta:"Explore the collection"},
 buy:{label:"PRIVATE ACQUISITION",title:"Find a home beyond expectation",copy:"From private search to considered negotiation, we make acquiring an exceptional property feel precise and personal.",img:"photo-1600585154340-be6161a56a0c",cta:"Start your property search"},
 sell:{label:"SELLING WITH AURELIA",title:"Your home deserves exceptional representation",copy:"Strategic positioning, cinematic presentation, qualified outreach and discreet negotiation for singular homes.",img:"photo-1600047509807-ba8f99d2cdde",cta:"Request a property valuation"},
 neighborhoods:{label:"CURATED PLACES",title:"A way of living",copy:"Editorial guides to Westlake Hills, Downtown Austin, Malibu, Beverly Hills, Manhattan and Scottsdale. Market figures are illustrative for this portfolio concept.",img:"photo-1494526585095-c41746248156",cta:"Explore neighborhood guides"},
 about:{label:"THE AURELIA APPROACH",title:"Considered at every turn",copy:"A boutique, modern approach built around curation, local intelligence, discretion, exceptional presentation and personal service.",img:"photo-1600566753086-00f18fb6b3ea",cta:"Meet our advisors"},
 agents:{label:"PRIVATE ADVISORY",title:"Expertise, personally delivered",copy:"Meet fictional advisors Elena Marlowe, Julian Hart, Amara Vale and Theo Laurent—created for this portfolio experience.",img:"photo-1556761175-b413da4baf72",cta:"Arrange a consultation"},
 journal:{label:"NOTES ON HOME & PLACE",title:"The Aurelia Journal",copy:"Perspectives on architecture, modern luxury, discerning acquisition and the enduring relationship between location and value.",img:"photo-1618221195710-dd6b41faaea6",cta:"Read the latest story"},
 contact:{label:"PRIVATE CONSULTATION",title:"Let’s begin a conversation",copy:"Tell us what you are looking for—or what you are considering selling. Demo office: 18 Aurelia Row, Austin. (512) 555-0188.",img:"photo-1600566753190-17f0baa2a6c3",cta:"Send an inquiry"},
 privacy:{label:"PORTFOLIO CONCEPT",title:"Privacy policy",copy:"This fictional demonstration does not submit data to a live backend. Form entries remain in your browser session and are not used for marketing.",img:"photo-1600607687939-ce8a6c25118c",cta:"Return home"}
};
export default async function Page({params}:{params:Promise<{slug:string[]}>}){const{slug}=await params;const key=slug[0];const d=data[key]||data.journal;return <main id="main" className="inner"><header className="innerNav"><Link href="/" className="brand">AURELIA <span>ESTATES</span></Link><Link href="/properties">Properties</Link><Link href="/contact" className="navCta">Private Consultation</Link></header><section className="innerHero" style={{backgroundImage:`linear-gradient(90deg,#13251ddd,transparent),url(https://images.unsplash.com/${d.img}?auto=format&fit=crop&w=2200&q=85)`}}><p className="eyebrow">{d.label}</p><h1>{d.title}</h1><p>{d.copy}</p></section><section className="innerBody"><p className="eyebrow dark">AURELIA ESTATES</p><h2>{key==="sell"?"Tell us about your property.":key==="contact"?"How may we help?":"A thoughtful, private experience."}</h2><p>{key==="privacy"?"To prepare this concept for a real client, connect forms to a secure processor and replace the policy with counsel-approved language.":"Every Aurelia engagement begins by listening. Share a few details and a fictional advisor will prepare a tailored next step for this demonstration."}</p>{key!=="privacy"&&<form className="consult"><label>Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="Email address"/></label><label>What can we help with?<select><option>Buying a property</option><option>Selling a property</option><option>Private consultation</option></select></label><label>Message<textarea rows={4} placeholder="Tell us a little more"/></label><button>{d.cta} →</button></form>}<Link href="/" className="back">← Return to Aurelia Estates</Link></section></main>}
